// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smalltalks.Data;

#nullable disable

namespace Smalltalks.Migrations
{
    [DbContext(typeof(SmallTalksDBContext))]
    [Migration("20240709152625_InitialDB2")]
    partial class InitialDB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smalltalks.Models.SalutationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Salutations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Bom dia"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Boa tarde"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Boa noite"
                        });
                });

            modelBuilder.Entity("Smalltalks.Models.SwearingModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Swearings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Caralho"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Cacete"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Puta"
                        });
                });

            modelBuilder.Entity("Smalltalks.Models.ToThankModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("ToThanks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Obrigado"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Agradecido"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Agradeço"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
