// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smalltalks.Data;

#nullable disable

namespace Smalltalks.Migrations
{
    [DbContext(typeof(SmallTalksDBContext))]
    partial class SmallTalksDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smalltalks.Models.SalutationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Salutations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Bom dia"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Boa tarde"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Boa noite"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Oi"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Tudo bem?"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Olá"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Como vai?"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "E ai"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Beleza?"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Bom dia!"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Boa tarde!"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Boa noite!"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Como você está?"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Como você está se sentindo hoje?"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Tudo em ordem?"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Que tal"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Como estão as coisas?"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Beleza pura?"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Bom te ver!"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Como tem passado?"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "De boa?"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Que prazer te encontrar!"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Tudo joia?"
                        });
                });

            modelBuilder.Entity("Smalltalks.Models.SwearingModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Swearings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Caralho"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Cacete"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Puta"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "É foda"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "E ai"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Homossexual"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Gay"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Caralho"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Que merda"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Porra"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Tudo em ordem?"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Filho da puta"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Vai tomar no cu"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Tomar no cu"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Viado"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Boceta"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Macaco"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Macaca"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Pau"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Pau no cu"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Piroca"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Corno"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Corna"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Vagabunda"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Vagabundo"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Toma no cu"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Filha da puta"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Foda"
                        });
                });

            modelBuilder.Entity("Smalltalks.Models.ToThankModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("ToThanks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Obrigado"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Agradecido"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Agradeço"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Obrigado"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Grato"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Agradeço"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Valeu"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Muito obrigado"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Obrigadão"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Obrigadíssimo"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Agradecimento"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Gratidão"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Obrigadinho"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Muito obrigada"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Agradecendo"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Agradecidamente"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Agradeço muito"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Fico grato"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Agradecemos"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Muito agradecido"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Obrigada"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Agradecida"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Grata"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Obrigadona"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Fico grata"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Muito agradecida"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
